name: OnlineManagement
version: 1.0.1
author: Shadow48402
main: nl.nielsha.plugins.onlinemanagement.OnlineManagement
commands:
  om:
    description: Online Management Main Command
  online:
    description: Check the online players in the server!