name: OnlineManagement
version: 1.0.4.2
author: Shadow48402
main: nl.nielsha.plugins.onlinemanagement.OnlineManagement
commands:
  om:
    description: Online Management Main Command
  online:
    description: Check the online players in the server!
  staff:
    description: Create, control and watch the staff list
  ban:
    description: Ban someone with your banhammer >:)
  unban:
    description: Say pardon to someone you banned