name: OnlineManagement
version: 1.0.6
author: Shadow48402
main: nl.nielsha.plugins.onlinemanagement.OnlineManagement
commands:
  om:
    description: Online Management Main Command
  online:
    description: Check the online players in the server!
  staff:
    description: Create, control and watch the staff list
  friend:
    description: Manage your friend list, add, remove, look.